export const VALID_CATEGORIES = [
    "Comida rápida",
    "Moda",
    "Salud y belleza",
    "Servicios financieros",
    "Inmuebles",
    "Entretenimiento",
    "Servicios profesionales",
    "Automóviles",
    "Turismo",
    "Tiendas en línea",
    "Comercio minorista",
    "Construcción",
    "Educación",
    "Gran industria",
    "Servicios públicos",
    "Servicios al cliente",
    "Transporte",
    "Servicios públicos",
    "Servicios al cliente",
    "Transporte",
];
